Visited stories
gyvosistorijos/gyvos-istorijos-android pull request #27
Opened 2016-11-26 18:29 UTC by vycius

![screenshot_20161126-202610](https://cloud.githubusercontent.com/assets/3719141/20642408/c0e5740a-b416-11e6-816f-282723bf7a73.png)

* Save visited stories to Realm db;
* Show different markers for visited stories;
* Let user always click on visited stories markers;

I have an idea to implement user collected stories list https://github.com/gyvosistorijos/gyvos-istorijos-android/issues/23 after this

2016-11-28 23:02 UTC, justasm requested changes
I get a crash on launch due to a missing migration.
```
io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
// ...
Caused by: io.realm.exceptions.RealmMigrationNeededException: The 'VisitedStoryRealm' class is missing from the schema for this Realm.
```

2016-11-28 23:02 UTC, justasm commented on app/src/main/java/lt/gyvosistorijos/entity/VisitedStory.kt
> +        val story: Story
`VisitedStory` doesn't need a story object.

2016-11-29 07:58 UTC, vycius commented
Thanks. I will fix migration issue and remove `Story` from `VisitedStory`. Could you give color codes for visited place marker ?

2016-11-29 08:48 UTC, justasm commented
Since we're using cold colours for the markers you could try a softer cold colour e.g. B8EEDE and 87AEA3

2016-11-29 21:51 UTC, justasm approved these changes
Will have to look into proper migrations in the future 🙂

2016-11-29 21:53 UTC, merged